"""Base Mario environment wrapper around stable-retro.

``MarioEnv`` registers the SuperMarioBros-Nes custom integration, creates
the retro environment, and provides low-level utilities used by all higher-
level wrappers:

- Loading gzip-compressed ``.state`` files into the emulator.
- Computing the composite X-position from two RAM bytes.
- Exposing a clean ``info`` dict on every ``step()``.

The class follows the ``gymnasium.Env`` interface (new-style API):
``reset()`` → ``(obs, info)``, ``step()`` → ``(obs, reward, terminated, truncated, info)``.
"""

from __future__ import annotations

import gzip
import logging
from pathlib import Path
from typing import Any

import numpy as np

try:
    import stable_retro as retro
except ImportError as exc:
    raise ImportError(
        "stable-retro is not installed. Run `bash setup.sh` to set up the environment."
    ) from exc

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GAME_NAME = "SuperMarioBros-Nes"

# Path to the stimuli directory that contains the SuperMarioBros-Nes integration.
# Using the copy bundled with the MariHA dataset so the environment is fully
# self-contained and does not depend on system-wide retro data.
import os

_REPO_ROOT = Path(__file__).resolve().parents[2]  # MariHA/
_DATA_ROOT = Path(os.environ["MARIHA_DATA_ROOT"]) if "MARIHA_DATA_ROOT" in os.environ else _REPO_ROOT / "data"
STIMULI_PATH = _DATA_ROOT / "mario" / "stimuli"

# Scenarios generated by scenario_gen.py live here.
SCENARIOS_DIR = Path(__file__).resolve().parent / "scenarios"

# Default upscaling factor for the ``human`` render window.  The NES frame is
# 256x224, which is tiny on modern displays; we multiply both dimensions by
# this factor so the emulator window is comfortably sized by default.
HUMAN_RENDER_SCALE = 4

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_state_bytes(state_file: Path) -> bytes:
    """Load a gzip-compressed ``.state`` file and return raw emulator bytes.

    Args:
        state_file: Path to the ``.state`` file.

    Returns:
        Decompressed emulator RAM bytes.

    Raises:
        FileNotFoundError: If ``state_file`` does not exist.
    """
    if not state_file.exists():
        raise FileNotFoundError(f"State file not found: {state_file}")
    with gzip.open(state_file, "rb") as fh:
        return fh.read()


def _make_scaled_viewer(scale: int):
    """Create a ``SimpleImageViewer`` whose window is ``scale``× the frame.

    ``stable_retro``'s ``SimpleImageViewer`` sizes its pyglet window from the
    first image passed to ``imshow`` (and caps it at ``maxwidth=500``).  We
    return a thin subclass that, on the first call, feeds an upscaled copy of
    the frame so the window is created at ``scale``× the native NES
    resolution.  All subsequent frames are passed through unchanged — the
    existing GL viewport code stretches them to the window with the
    nearest-neighbor filter already set upstream.
    """
    from stable_retro.rendering import SimpleImageViewer

    class _ScaledImageViewer(SimpleImageViewer):
        def __init__(self) -> None:
            # Set maxwidth high enough that the scaled frame is never capped.
            super().__init__(maxwidth=10**9)
            self._scale = scale

        def imshow(self, arr, rotation=0):  # type: ignore[override]
            if self.window is None and self._scale != 1:
                arr = np.repeat(
                    np.repeat(arr, self._scale, axis=0),
                    self._scale,
                    axis=1,
                )
            super().imshow(arr, rotation=rotation)

    return _ScaledImageViewer()


def compute_x_position(info: dict[str, Any]) -> int:
    """Compute the absolute X-position from two RAM bytes.

    The NES stores Mario's absolute X-position as a 16-bit value split
    across two RAM addresses::

        x_pos = player_x_posHi * 256 + player_x_posLo

    Args:
        info: The ``info`` dict returned by a stable-retro ``step()`` call.

    Returns:
        Mario's absolute X-position as an integer.
    """
    return int(info["player_x_posHi"]) * 256 + int(info["player_x_posLo"])


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------


class MarioEnv:
    """Thin wrapper around the stable-retro SuperMarioBros-Nes environment.

    Registers the custom integration on first instantiation, creates the
    underlying retro environment with a per-scene ``scenario.json``, and
    provides helpers for state loading and X-position computation.

    This class is meant to be used through ``SceneEnv``, not directly.

    Args:
        scene_id: Scene identifier (e.g. ``'w1l1s0'``), used to select the
            corresponding ``scenario.json``.
        render_mode: Passed to ``stable_retro.make()``.  Use ``'human'`` for
            a live display or ``None`` (default) for headless training.
        stimuli_path: Override path to the stimuli directory.  Defaults to
            ``MariHA/data/mario/stimuli``.
        scenarios_dir: Override path to the scenario files directory.

    Attributes:
        observation_space: gymnasium observation space (H × W × C uint8 pixels).
        action_space: stable-retro MultiBinary action space (raw NES buttons).
            Replaced by a discrete space in ``ActionWrapper``.
        info_keys: RAM variable names exposed in the info dict.
    """

    def __init__(
        self,
        scene_id: str,
        render_mode: str | None = None,
        stimuli_path: Path = STIMULI_PATH,
        scenarios_dir: Path = SCENARIOS_DIR,
    ) -> None:
        self.scene_id = scene_id
        self._render_mode = render_mode

        # Register the custom integration once per process.
        retro.data.Integrations.add_custom_path(str(stimuli_path))

        scenario_file = scenarios_dir / f"{scene_id}.json"
        if not scenario_file.exists():
            raise FileNotFoundError(
                f"Scenario file not found: {scenario_file}. "
                "Run `mariha-generate-scenarios` first."
            )

        self._env = retro.make(
            GAME_NAME,
            inttype=retro.data.Integrations.CUSTOM_ONLY,
            render_mode=render_mode,
            scenario=str(scenario_file),
        )

        # Pre-install a scaled viewer so the ``human`` render window opens at
        # ``HUMAN_RENDER_SCALE``× the native NES resolution instead of the
        # tiny (and maxwidth-capped) default.  ``retro_env.render()`` only
        # creates its own viewer when ``self.viewer`` is ``None``, so
        # assigning here before the first render is enough.
        if render_mode == "human" and HUMAN_RENDER_SCALE != 1:
            self._env.viewer = _make_scaled_viewer(HUMAN_RENDER_SCALE)

        self.observation_space = self._env.observation_space
        self.action_space = self._env.action_space

        self._prev_x: int = 0
        self._last_time: int | None = None
        self._curr_lives: int = 0
        self._curr_score: int = 0

    # ------------------------------------------------------------------
    # State loading
    # ------------------------------------------------------------------

    def _load_state(self, state_file: Path) -> None:
        """Load a ``.state`` file into the emulator.

        Args:
            state_file: Path to the gzip-compressed ``.state`` file.
        """
        self._env.initial_state = load_state_bytes(state_file)

    # ------------------------------------------------------------------
    # gymnasium interface
    # ------------------------------------------------------------------

    def reset(
        self,
        state_file: Path | None = None,
        seed: int | None = None,
    ) -> tuple[np.ndarray, dict]:
        """Reset the environment.

        Args:
            state_file: If provided, load this ``.state`` before resetting.
            seed: Optional RNG seed (passed to the underlying env).

        Returns:
            ``(observation, info)`` tuple.
        """
        if state_file is not None:
            self._load_state(state_file)

        obs, _empty_info = self._env.reset(seed=seed)
        # stable-retro reset() always returns {} as info; read RAM variables
        # directly via data.lookup_all() which is populated after reset().
        info = self._env.data.lookup_all()
        self._prev_x = compute_x_position(info)
        self._last_time = None
        self._curr_lives = int(info.get("lives", 0))
        self._curr_score = int(info.get("score", 0))
        return obs, self._enrich_info(info)

    def step(
        self, action: np.ndarray
    ) -> tuple[np.ndarray, float, bool, bool, dict]:
        obs, _retro_reward, terminated, truncated, _step_info = self._env.step(action)
        info = self._env.data.lookup_all()

        reward = 0.0

        time_val = int(info.get("time", 0))
        if self._last_time is not None:
            reward += min(time_val - self._last_time, 0)
        self._last_time = time_val

        x_pos = compute_x_position(info)
        diff_x = x_pos - self._prev_x
        reward += diff_x if -5 <= diff_x <= 5 else 0
        self._prev_x = x_pos

        lives = int(info.get("lives", 0))
        if lives < self._curr_lives:
            reward -= 15
            self._curr_lives = lives

        reward = max(min(reward, 15), -15)

        score = int(info.get("score", 0))
        reward += min((score - self._curr_score) / 4.0, 50)
        self._curr_score = score

        return obs, reward, terminated, truncated, self._enrich_info(info)

    def render(self) -> np.ndarray | None:
        """Render the current frame."""
        return self._env.render()

    def close(self) -> None:
        """Close the underlying retro environment."""
        self._env.close()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _enrich_info(self, info: dict) -> dict:
        """Add derived fields to the info dict.

        Adds ``x_pos`` (composite 16-bit X-position) so callers do not need
        to recompute it.

        Args:
            info: Raw info dict from stable-retro.

        Returns:
            Enriched info dict.
        """
        enriched = dict(info)
        enriched["x_pos"] = compute_x_position(info)
        return enriched

    # ------------------------------------------------------------------
    # Properties forwarded from the inner env
    # ------------------------------------------------------------------

    @property
    def unwrapped(self):
        """The raw stable-retro environment."""
        return self._env
