"""Base Mario environment wrapper around stable-retro.

``MarioEnv`` registers the SuperMarioBros-Nes custom integration, creates
the retro environment, and provides low-level utilities used by all higher-
level wrappers:

- Loading gzip-compressed ``.state`` files into the emulator.
- Computing the composite X-position from two RAM bytes.
- Exposing a clean ``info`` dict on every ``step()``.

The class follows the ``gymnasium.Env`` interface (new-style API):
``reset()`` → ``(obs, info)``, ``step()`` → ``(obs, reward, terminated, truncated, info)``.
"""

from __future__ import annotations

import gzip
import logging
from pathlib import Path
from typing import Any

import numpy as np

try:
    import stable_retro as retro
except ImportError as exc:
    raise ImportError(
        "stable-retro is not installed. Run `bash setup.sh` to set up the environment."
    ) from exc

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GAME_NAME = "SuperMarioBros-Nes"

# Path to the stimuli directory that contains the SuperMarioBros-Nes integration.
# Using the copy bundled with the MariHA dataset so the environment is fully
# self-contained and does not depend on system-wide retro data.
_REPO_ROOT = Path(__file__).resolve().parents[2]  # MariHA/
STIMULI_PATH = _REPO_ROOT / "data" / "mario" / "stimuli"

# Scenarios generated by scenario_gen.py live here.
SCENARIOS_DIR = Path(__file__).resolve().parent / "scenarios"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_state_bytes(state_file: Path) -> bytes:
    """Load a gzip-compressed ``.state`` file and return raw emulator bytes.

    Args:
        state_file: Path to the ``.state`` file.

    Returns:
        Decompressed emulator RAM bytes.

    Raises:
        FileNotFoundError: If ``state_file`` does not exist.
    """
    if not state_file.exists():
        raise FileNotFoundError(f"State file not found: {state_file}")
    with gzip.open(state_file, "rb") as fh:
        return fh.read()


def compute_x_position(info: dict[str, Any]) -> int:
    """Compute the absolute X-position from two RAM bytes.

    The NES stores Mario's absolute X-position as a 16-bit value split
    across two RAM addresses::

        x_pos = player_x_posHi * 256 + player_x_posLo

    Args:
        info: The ``info`` dict returned by a stable-retro ``step()`` call.

    Returns:
        Mario's absolute X-position as an integer.
    """
    return int(info["player_x_posHi"]) * 256 + int(info["player_x_posLo"])


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------


class MarioEnv:
    """Thin wrapper around the stable-retro SuperMarioBros-Nes environment.

    Registers the custom integration on first instantiation, creates the
    underlying retro environment with a per-scene ``scenario.json``, and
    provides helpers for state loading and X-position computation.

    This class is meant to be used through ``SceneEnv``, not directly.

    Args:
        scene_id: Scene identifier (e.g. ``'w1l1s0'``), used to select the
            corresponding ``scenario.json``.
        render_mode: Passed to ``stable_retro.make()``.  Use ``'human'`` for
            a live display or ``None`` (default) for headless training.
        stimuli_path: Override path to the stimuli directory.  Defaults to
            ``MariHA/data/mario/stimuli``.
        scenarios_dir: Override path to the scenario files directory.

    Attributes:
        observation_space: gymnasium observation space (H × W × C uint8 pixels).
        action_space: stable-retro MultiBinary action space (raw NES buttons).
            Replaced by a discrete space in ``ActionWrapper``.
        info_keys: RAM variable names exposed in the info dict.
    """

    def __init__(
        self,
        scene_id: str,
        render_mode: str | None = None,
        stimuli_path: Path = STIMULI_PATH,
        scenarios_dir: Path = SCENARIOS_DIR,
    ) -> None:
        self.scene_id = scene_id
        self._render_mode = render_mode

        # Register the custom integration once per process.
        retro.data.Integrations.add_custom_path(str(stimuli_path))

        scenario_file = scenarios_dir / f"{scene_id}.json"
        if not scenario_file.exists():
            raise FileNotFoundError(
                f"Scenario file not found: {scenario_file}. "
                "Run `mariha-generate-scenarios` first."
            )

        self._env = retro.make(
            GAME_NAME,
            inttype=retro.data.Integrations.CUSTOM_ONLY,
            render_mode=render_mode,
            scenario=str(scenario_file),
        )

        self.observation_space = self._env.observation_space
        self.action_space = self._env.action_space

        # Track X-position between steps for delta-X reward.
        self._prev_x: int = 0

    # ------------------------------------------------------------------
    # State loading
    # ------------------------------------------------------------------

    def _load_state(self, state_file: Path) -> None:
        """Load a ``.state`` file into the emulator.

        Args:
            state_file: Path to the gzip-compressed ``.state`` file.
        """
        self._env.initial_state = load_state_bytes(state_file)

    # ------------------------------------------------------------------
    # gymnasium interface
    # ------------------------------------------------------------------

    def reset(
        self,
        state_file: Path | None = None,
        seed: int | None = None,
    ) -> tuple[np.ndarray, dict]:
        """Reset the environment.

        Args:
            state_file: If provided, load this ``.state`` before resetting.
            seed: Optional RNG seed (passed to the underlying env).

        Returns:
            ``(observation, info)`` tuple.
        """
        if state_file is not None:
            self._load_state(state_file)

        obs, _empty_info = self._env.reset(seed=seed)
        # stable-retro reset() always returns {} as info; read RAM variables
        # directly via data.lookup_all() which is populated after reset().
        info = self._env.data.lookup_all()
        self._prev_x = compute_x_position(info)
        return obs, self._enrich_info(info)

    def step(
        self, action: np.ndarray
    ) -> tuple[np.ndarray, float, bool, bool, dict]:
        """Step the environment with a raw NES button array.

        Reward is the change in absolute X-position since the last step.

        Args:
            action: MultiBinary NES button array (length 9).

        Returns:
            ``(obs, reward, terminated, truncated, info)`` tuple.
        """
        obs, _retro_reward, terminated, truncated, info = self._env.step(action)
        x_pos = compute_x_position(info)
        reward = float(x_pos - self._prev_x)
        self._prev_x = x_pos
        return obs, reward, terminated, truncated, self._enrich_info(info)

    def render(self) -> np.ndarray | None:
        """Render the current frame."""
        return self._env.render()

    def close(self) -> None:
        """Close the underlying retro environment."""
        self._env.close()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _enrich_info(self, info: dict) -> dict:
        """Add derived fields to the info dict.

        Adds ``x_pos`` (composite 16-bit X-position) so callers do not need
        to recompute it.

        Args:
            info: Raw info dict from stable-retro.

        Returns:
            Enriched info dict.
        """
        enriched = dict(info)
        enriched["x_pos"] = compute_x_position(info)
        return enriched

    # ------------------------------------------------------------------
    # Properties forwarded from the inner env
    # ------------------------------------------------------------------

    @property
    def unwrapped(self):
        """The raw stable-retro environment."""
        return self._env
