#!/bin/bash
#SBATCH --job-name=mariha_all
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --error=logs/%x_%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --array=0-149

# Full benchmark sweep: every agent x every subject x every CL method.
# Each array task is one independent job (one mariha-run-cl invocation).
#
#   3 agents x 5 subjects x 10 CL options = 150 jobs (array 0-149)
#
# Environment (modules, venv, MARIHA_* paths, SLURM account) all comes from
# the env file generated by setup_hpc.sh — nothing is hardcoded here.

# Load the setup_hpc.sh-generated environment. Override its location with
# MARIHA_ENV_FILE if needed.
MARIHA_ENV_FILE="${MARIHA_ENV_FILE:-$HOME/.config/mariha/hpc_env.sh}"
if [[ ! -f "$MARIHA_ENV_FILE" ]]; then
    echo "ERROR: MariHA HPC env file not found at $MARIHA_ENV_FILE" >&2
    echo "  Run setup_hpc.sh on a login node first — it generates this file." >&2
    exit 1
fi
source "$MARIHA_ENV_FILE"

# Run this script directly — it submits itself as a SLURM array job, using the
# allocation account recorded by setup_hpc.sh (MARIHA_SLURM_ACCOUNT). Inside an
# array task SLURM_ARRAY_TASK_ID is set, so we fall through to the real work.
# Extra args are forwarded to sbatch and override the account, e.g.:
#   ./scripts/hpc_run_all.sh --account=def-other
if [[ -z "${SLURM_ARRAY_TASK_ID:-}" ]]; then
    echo "Submitting MariHA benchmark sweep (150-task array) ..."
    SBATCH_ARGS=()
    if [[ -n "${MARIHA_SLURM_ACCOUNT:-}" ]]; then
        SBATCH_ARGS+=(--account="$MARIHA_SLURM_ACCOUNT")
    else
        echo "  No MARIHA_SLURM_ACCOUNT set — pass --account=def-yourpi or" >&2
        echo "  re-run setup_hpc.sh --account=def-yourpi." >&2
    fi
    exec sbatch "${SBATCH_ARGS[@]}" "$@" "$0"
fi

AGENTS=(sac ppo dqn)
SUBJECTS=(sub-01 sub-02 sub-03 sub-05 sub-06)
CL_METHODS=(agem clonex der ewc l2 mas multitask packnet si none)

N_CL=${#CL_METHODS[@]}        # 10
N_SUBJ=${#SUBJECTS[@]}        # 5

# Decompose the flat array index into (agent, subject, cl_method).
IDX=$SLURM_ARRAY_TASK_ID
CL_METHOD=${CL_METHODS[$(( IDX % N_CL ))]}
SUBJECT=${SUBJECTS[$(( (IDX / N_CL) % N_SUBJ ))]}
AGENT=${AGENTS[$(( IDX / (N_CL * N_SUBJ) ))]}

mkdir -p logs

# Prevent TF from pre-allocating all GPU VRAM on startup.
export TF_FORCE_GPU_ALLOW_GROWTH=true

echo "Task $IDX: agent=$AGENT subject=$SUBJECT cl_method=$CL_METHOD"

if [ "$CL_METHOD" = "none" ]; then
    mariha-run-cl --agent "$AGENT" --subject "$SUBJECT" --seed 0 --progress off
else
    mariha-run-cl --agent "$AGENT" --cl_method "$CL_METHOD" \
        --subject "$SUBJECT" --seed 0 --progress off
fi
