#!/bin/bash
#SBATCH --account=def-YOUR_PI        # replace with your allocation
#SBATCH --job-name=mariha_all
#SBATCH --output=logs/%x_%A_%a.out
#SBATCH --error=logs/%x_%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --array=0-149

# Full benchmark sweep: every agent x every subject x every CL method.
# Each array task is one independent job (one mariha-run-cl invocation).
#
#   3 agents x 5 subjects x 10 CL options = 150 jobs (array 0-149)
#
# All environment setup (modules, venv, data/repo paths) is read from the
# env file generated by setup_hpc.sh — see the source line below.

AGENTS=(sac ppo dqn)
SUBJECTS=(sub-01 sub-02 sub-03 sub-05 sub-06)
CL_METHODS=(agem clonex der ewc l2 mas multitask packnet si none)

N_CL=${#CL_METHODS[@]}        # 10
N_SUBJ=${#SUBJECTS[@]}        # 5

# This is a SLURM array job — submit it, do not run it directly:
#   cd <repo> && sbatch scripts/hpc_run_all.sh
if [[ -z "${SLURM_ARRAY_TASK_ID:-}" ]]; then
    echo "ERROR: SLURM_ARRAY_TASK_ID is unset — this script must be submitted, not run directly." >&2
    echo "  cd <repo> && sbatch scripts/hpc_run_all.sh" >&2
    exit 1
fi

# Decompose the flat array index into (agent, subject, cl_method).
IDX=$SLURM_ARRAY_TASK_ID
CL_METHOD=${CL_METHODS[$(( IDX % N_CL ))]}
SUBJECT=${SUBJECTS[$(( (IDX / N_CL) % N_SUBJ ))]}
AGENT=${AGENTS[$(( IDX / (N_CL * N_SUBJ) ))]}

mkdir -p logs

# Modules, venv activation and MARIHA_* paths all come from the env file
# written by setup_hpc.sh — no module loads or paths are hardcoded here.
# Override the location with MARIHA_ENV_FILE if needed.
MARIHA_ENV_FILE="${MARIHA_ENV_FILE:-$HOME/.config/mariha/hpc_env.sh}"
if [[ ! -f "$MARIHA_ENV_FILE" ]]; then
    echo "ERROR: MariHA HPC env file not found at $MARIHA_ENV_FILE" >&2
    echo "  Run setup_hpc.sh on a login node first — it generates this file." >&2
    exit 1
fi
source "$MARIHA_ENV_FILE"

# Prevent TF from pre-allocating all GPU VRAM on startup.
export TF_FORCE_GPU_ALLOW_GROWTH=true

echo "Task $IDX: agent=$AGENT subject=$SUBJECT cl_method=$CL_METHOD"

if [ "$CL_METHOD" = "none" ]; then
    mariha-run-cl --agent "$AGENT" --subject "$SUBJECT" --seed 0 --progress off
else
    mariha-run-cl --agent "$AGENT" --cl_method "$CL_METHOD" \
        --subject "$SUBJECT" --seed 0 --progress off
fi
